version: 0.2
env:
  variables:
    DESTINATION: 2019-06-27_10-42_continue_section_3
    REPORT_URL: >-
      https://TEST RESULT BUCKET
      HERE.s3.amazonaws.com/2019-06-27_10-42_continue_section_3/mochawesome.html
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - echo $DESTINATION
      - echo $REPORT_URL
      - echo "building this job from programmatically generated buildspec.yml!"
      - npm install
      - >-
        apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3
        libxss1 libasound2 xvfb
      - echo this is last commitMessage ==> continue_section_3
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run ci
      - >-
        aws s3 mv mochawesome-report s3://TEST RESULT BUCKET
        HERE/2019-06-27_10-42_continue_section_3 --recursive
      - >-
        aws sns publish --topic-arn SNS TOPIC HERE --subject "CodeBuild Tests
        2019-06-27_10-42_continue_section_3" --message "CodeBuild tests have
        completed for last commit message : continue_section_3 . Follow link
        here to report results :  https://TEST RESULT BUCKET
        HERE.s3.amazonaws.com/2019-06-27_10-42_continue_section_3/mochawesome.html"
artifacts:
  files:
    - index.html
    - assets/**/*
    - css/*
    - js/*
    - fonts/*
  base-directory: dist
