version: 0.2
env:
  variables:
    DESTINATION: 2019-06-27_11-53_change_job_access_for_codebuild
    REPORT_URL: >-
      https://testresultscypress.s3.amazonaws.com/2019-06-27_11-53_change_job_access_for_codebuild/mochawesome.html
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - echo $DESTINATION
      - echo $REPORT_URL
      - echo "building this job from programmatically generated buildspec.yml!"
      - npm install
      - >-
        apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3
        libxss1 libasound2 xvfb
      - echo this is last commitMessage ==> change_job_access_for_codebuild
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run ci
      - >-
        aws s3 mv mochawesome-report
        s3://testresultscypress/2019-06-27_11-53_change_job_access_for_codebuild
        --recursive
      - >-
        aws sns publish --topic-arn
        arn:aws:sns:us-west-2:422539116740:cypressnotification --subject
        "CodeBuild Tests 2019-06-27_11-53_change_job_access_for_codebuild"
        --message "CodeBuild tests have completed for last commit message :
        change_job_access_for_codebuild . Follow link here to report results : 
        https://testresultscypress.s3.amazonaws.com/2019-06-27_11-53_change_job_access_for_codebuild/mochawesome.html"
artifacts:
  files:
    - index.html
    - assets/**/*
    - css/*
    - js/*
    - fonts/*
  base-directory: dist
